### ISSUE TITLE
I think we need an APITimeout exception.

### ISSUE THREAD

**Issue by deonbredenhann** [yola/ultradns#6]
related to https://github.com/yola/ybot/issues/604

After some testing I found that, when we get a 504 timeout from UltraDNS, the response body is always empty. This makes the reponse.json() throw a ValueError. It would be nice to return a different error when this happens, so we can retry. The call always (In my tests) completes on the UltraDNS side, but we don't know it, as the client died with a json decode error.

**Comment by ekoval** [comment]
Done: https://github.com/yola/ultradns/pull/7
